### PR TITLE
Correctly support ACC128

### LINKED ISSUE #96: Zero opcode when unrolling loops in the sandbox ABI
Compiling the following code fragment (a heavily-trimmed edition of openssl's `crypto/bn/bn_asm.c`) with loop unrolling activated:
`clang -integrated-as -msoft-float -O1 -funroll-loops -mabi=sandbox -pipe -std=gnu89 --target=cheri-unknown-freebsd -c example.c -o example.o`

Results in a zero opcode:
`fatal error: error in backend: Not supported instr: <MCInst 0 <MCOperand Reg:360> <MCOperand Reg:219> <MCOperand Imm:0> <MCOperand Reg:42>>`

```C++
#define BN_MASK2l	(0xffffffffL)
#define BN_MASK2h	(0xffffffff00000000L)

unsigned long bn_div_words(unsigned long h, unsigned long l, unsigned long d) {
    unsigned long dh, q, th, tl, t;

    dh = d >> 32;
    for (int count = 0; count < 2; count++) {
        if ((h >> 32) == dh)
            q = BN_MASK2l;
        else
            q = h / dh;

        th = q * dh;
        tl = d * q;
        while (1) {
            t = h - th;
            if ((t & BN_MASK2h))
                break;
            q--;
            th -= dh;
            tl -= d;
        }
        t = (tl >> 32);
        tl = (tl << 32) & BN_MASK2h;
        th += t;

        h -= th;
    }
    return 0;
}

```

### PR DESCRIPTION
**Pull request by ChrisKitching**
We were aborting with "unexpected register type for CHERI!" for, it eventually turned out, no good reason.
The STORE/LOAD_ACC128 pseudos feed back into storeRegToStack and friends when they're lowered, so our existing CHERI-ifying logic is sufficient, we just have to stop throwing a tantrum when we see this type of register.

Fixes #96

### CODE REVIEW

File: lib/Target/Mips/MipsSEInstrInfo.cpp [hunk 1]
```diff
@@ -225,7 +228,7 @@ storeRegToStack(MachineBasicBlock &MBB, MachineBasicBlock::iterator I,
       llvm_unreachable("Unexpected register type for CHERI!");
     }
     BuildMI(MBB, I, DL, get(Opc)).addReg(SrcReg, getKillRegState(isKill))
-      .addFrameIndex(FI).addImm(0).addMemOperand(MMO)
+      .addFrameIndex(FI).addImm(Offset).addMemOperand(MMO)
```
Comment (davidchisnall) [inline lib/Target/Mips/MipsSEInstrInfo.cpp]: Please can you make this fix (along with the corresponding oen elsewhere) a separate commit?

**Comment by davidchisnall** [comment]
This all looks good, but would look even better with a test case.  Did you manage to get the IR from clang to crash with llc and some option?

File: lib/Target/Mips/MipsSEInstrInfo.cpp (hunk 1 above)
Comment (ChrisKitching) [inline lib/Target/Mips/MipsSEInstrInfo.cpp]: It is a separate *commit* at the moment: you want a separate pull request, too?

**Comment by ChrisKitching** [comment]
Not yet: I'll do so next.

File: lib/Target/Mips/MipsSEInstrInfo.cpp (hunk 1 above)
Comment (ChrisKitching) [inline lib/Target/Mips/MipsSEInstrInfo.cpp]: (Assuming you're referring to all the s/0/Offset/ changes, instead of just some subset thereof)
